spring.application.name=snip
spring.datasource.url=jdbc:mysql://localhost:3306/urlshortenerdb
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

jwt.secret=22af987a10daccc3187e0d33f6442d6f5af196ca86484c4a4717555e34790122
jwt.expiration=172800000

logging.level.org.springframework.security=DEBUG
logging.level.org.urlshortner=DEBUG